spring:
  profiles:
    active: qa

springdoc:
  auto-tag-classes: true
  show-actuator: false
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
  swagger-ui:
    path: /swagger-ui.html

server:
  error:
    include-message: ALWAYS